sessionize_embed_block.settings:
  type: config_object
  label: Sessionize Embed Block Configuration
  mapping:
    embed_id:
      type: string
      label: Sessionize Embed ID
    embed_style:
      type: string
      label: Sessionize Embed Style
